apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: local-pvc
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/www/html"
          name: local-pvc